# Getting ready to test the workflow run on workflow dispatch with input selection event

name: Terraform CD
on:
  workflow_dispatch:
    inputs:
      env_select:
        description: "Select the environment to configure: "
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Check environment
        run: echo "Selected environment is ${{ github.event.inputs.env_select }}"

      - name: Checkout Codes
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: List the Terraform Workspaces
        run: terraform workspace list

      - name: Select the Envionment and set the Terraform Workspaces
        run: |
          terraform workspace select ${{ github.event.inputs.env_select }} || terraform workspace new ${{ github.event.inputs.env_select }}
          terraform workspace list

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var-file="${{ github.event.inputs.env_select }}.tfvars" -out="${{ github.event.inputs.env_select }}_tf_out"
      #  continue-on-error: true

      #- name: Terraform Apply
      #  run: terraform apply -auto-approve "${{ github.event.inputs.env_select }}_tf_out"

      #- name: Pause 3min to verify bucket creation
      #  run: sleep 180

      #- name: Terraform destroy
      #  run: terraform destroy -var-file=${{ github.event.inputs.choice }}.tfvars -auto-approve
